spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/farwydi/app-of-apps
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - "CreateNamespace=true"

apps:
  argocd:
    enabled: true
  cert-manager:
    enabled: true

argocd: {}
argocd-applicationset: {}
argocd-notifications: {}

cert-manager: {}
