---
# -- Values passed to the argo-cd chart
argo-cd:
  controller:
    metrics:
      serviceMonitor:
        enabled: false
  server:
    metrics:
      serviceMonitor:
        enabled: false
  repoServer:
    metrics:
      serviceMonitor:
        enabled: false

argocd-applicationset:
  installCRDs: false
