---
apiVersion: "v2"
name: "ingress-nginx"
version: "0"
description: |
  This chart installs Nginx and configures it as the default Kubernetes cluster Ingress Controller.
dependencies:
  - name: "ingress-nginx"
    version: "4.0.13"
    repository: "https://kubernetes.github.io/ingress-nginx"
